server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

logging:
  level:
    org.flywaydb: info
    root: INFO
    eddie.payment.orders: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
